version: '3'
services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - '27017:27017'
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=bossabox-vuttr
      - POSTGRES_USER=bossabox-vuttr
      - POSTGRESS_PASSWORD=bossabox-vuttr
    ports:
      - '5432:5432'
